version: "2"
run:
  go: "1.23"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dupword
    - durationcheck
    - err113
    - errchkjson
    - errname
    - exptostd
    - gocheckcompilerdirectives
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - interfacebloat
    - intrange
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nosprintfhostport
    - perfsprint
    - predeclared
    - protogetter
    - reassign
    - revive
    - sloglint
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
        - singleCaseSwitch
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
        text: do not define dynamic errors, use wrapped static errors instead
      - linters:
          - gosec
        text: 'G402: TLS InsecureSkipVerify may be true'
    paths:
      - tools
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - tools
      - third_party$
      - builtin$
      - examples$
