# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/master/.golangci.yaml as a
# reference.

run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goerr113
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - misspell
    - nestif
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

linters-settings:
  gosimple:
    go: "1.18"
  govet:
    enable-all: true
    disable:
      - fieldalignment
  staticcheck:
    go: "1.18"
  stylecheck:
    go: "1.18"
  unused:
    go: "1.18"

issues:
  exclude-rules:
    - linters: [goerr113]
      text: "do not define dynamic errors, use wrapped static errors instead"
    - linters: [gosec]
      text: "G402: TLS InsecureSkipVerify may be true"
    - linters: [typecheck]
      text: "is a program, not an importable package"
