// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.2
// source: ui/notifications.proto

package ui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Notification:
	//
	//	*Notification_ConnState
	//	*Notification_DataState
	//	*Notification_Status
	//	*Notification_NoPermission
	Notification  isNotification_Notification `protobuf_oneof:"notification"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_ui_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_ui_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_ui_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetNotification() isNotification_Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *Notification) GetConnState() *ConnectionState {
	if x != nil {
		if x, ok := x.Notification.(*Notification_ConnState); ok {
			return x.ConnState
		}
	}
	return nil
}

func (x *Notification) GetDataState() *DataState {
	if x != nil {
		if x, ok := x.Notification.(*Notification_DataState); ok {
			return x.DataState
		}
	}
	return nil
}

func (x *Notification) GetStatus() *GetStatusResponse {
	if x != nil {
		if x, ok := x.Notification.(*Notification_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *Notification) GetNoPermission() *NoPermission {
	if x != nil {
		if x, ok := x.Notification.(*Notification_NoPermission); ok {
			return x.NoPermission
		}
	}
	return nil
}

type isNotification_Notification interface {
	isNotification_Notification()
}

type Notification_ConnState struct {
	ConnState *ConnectionState `protobuf:"bytes,1,opt,name=conn_state,json=connState,proto3,oneof"`
}

type Notification_DataState struct {
	DataState *DataState `protobuf:"bytes,2,opt,name=data_state,json=dataState,proto3,oneof"`
}

type Notification_Status struct {
	Status *GetStatusResponse `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type Notification_NoPermission struct {
	NoPermission *NoPermission `protobuf:"bytes,4,opt,name=no_permission,json=noPermission,proto3,oneof"`
}

func (*Notification_ConnState) isNotification_Notification() {}

func (*Notification_DataState) isNotification_Notification() {}

func (*Notification_Status) isNotification_Notification() {}

func (*Notification_NoPermission) isNotification_Notification() {}

type ConnectionState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend is successfully connected to hubble-relay
	RelayConnected bool `protobuf:"varint,1,opt,name=relay_connected,json=relayConnected,proto3" json:"relay_connected,omitempty"`
	// Backend has lost the connection to hubble-relay and is reconnecting now
	RelayReconnecting bool `protobuf:"varint,2,opt,name=relay_reconnecting,json=relayReconnecting,proto3" json:"relay_reconnecting,omitempty"`
	// Backend has lost the connection to kubernetes and is reconnecting
	K8SUnavailable bool `protobuf:"varint,3,opt,name=k8s_unavailable,json=k8sUnavailable,proto3" json:"k8s_unavailable,omitempty"`
	// Backend has established connection to k8s
	K8SConnected  bool `protobuf:"varint,4,opt,name=k8s_connected,json=k8sConnected,proto3" json:"k8s_connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionState) Reset() {
	*x = ConnectionState{}
	mi := &file_ui_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionState) ProtoMessage() {}

func (x *ConnectionState) ProtoReflect() protoreflect.Message {
	mi := &file_ui_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionState.ProtoReflect.Descriptor instead.
func (*ConnectionState) Descriptor() ([]byte, []int) {
	return file_ui_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionState) GetRelayConnected() bool {
	if x != nil {
		return x.RelayConnected
	}
	return false
}

func (x *ConnectionState) GetRelayReconnecting() bool {
	if x != nil {
		return x.RelayReconnecting
	}
	return false
}

func (x *ConnectionState) GetK8SUnavailable() bool {
	if x != nil {
		return x.K8SUnavailable
	}
	return false
}

func (x *ConnectionState) GetK8SConnected() bool {
	if x != nil {
		return x.K8SConnected
	}
	return false
}

type DataState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// No pods in selected namespace
	NoActivity    bool `protobuf:"varint,1,opt,name=no_activity,json=noActivity,proto3" json:"no_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataState) Reset() {
	*x = DataState{}
	mi := &file_ui_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataState) ProtoMessage() {}

func (x *DataState) ProtoReflect() protoreflect.Message {
	mi := &file_ui_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataState.ProtoReflect.Descriptor instead.
func (*DataState) Descriptor() ([]byte, []int) {
	return file_ui_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *DataState) GetNoActivity() bool {
	if x != nil {
		return x.NoActivity
	}
	return false
}

type NoPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoPermission) Reset() {
	*x = NoPermission{}
	mi := &file_ui_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoPermission) ProtoMessage() {}

func (x *NoPermission) ProtoReflect() protoreflect.Message {
	mi := &file_ui_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoPermission.ProtoReflect.Descriptor instead.
func (*NoPermission) Descriptor() ([]byte, []int) {
	return file_ui_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *NoPermission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *NoPermission) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_ui_notifications_proto protoreflect.FileDescriptor

const file_ui_notifications_proto_rawDesc = "" +
	"\n" +
	"\x16ui/notifications.proto\x12\x02ui\x1a\x0fui/status.proto\"\xee\x01\n" +
	"\fNotification\x124\n" +
	"\n" +
	"conn_state\x18\x01 \x01(\v2\x13.ui.ConnectionStateH\x00R\tconnState\x12.\n" +
	"\n" +
	"data_state\x18\x02 \x01(\v2\r.ui.DataStateH\x00R\tdataState\x12/\n" +
	"\x06status\x18\x03 \x01(\v2\x15.ui.GetStatusResponseH\x00R\x06status\x127\n" +
	"\rno_permission\x18\x04 \x01(\v2\x10.ui.NoPermissionH\x00R\fnoPermissionB\x0e\n" +
	"\fnotification\"\xb7\x01\n" +
	"\x0fConnectionState\x12'\n" +
	"\x0frelay_connected\x18\x01 \x01(\bR\x0erelayConnected\x12-\n" +
	"\x12relay_reconnecting\x18\x02 \x01(\bR\x11relayReconnecting\x12'\n" +
	"\x0fk8s_unavailable\x18\x03 \x01(\bR\x0ek8sUnavailable\x12#\n" +
	"\rk8s_connected\x18\x04 \x01(\bR\fk8sConnected\",\n" +
	"\tDataState\x12\x1f\n" +
	"\vno_activity\x18\x01 \x01(\bR\n" +
	"noActivity\"@\n" +
	"\fNoPermission\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05errorb\x06proto3"

var (
	file_ui_notifications_proto_rawDescOnce sync.Once
	file_ui_notifications_proto_rawDescData []byte
)

func file_ui_notifications_proto_rawDescGZIP() []byte {
	file_ui_notifications_proto_rawDescOnce.Do(func() {
		file_ui_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ui_notifications_proto_rawDesc), len(file_ui_notifications_proto_rawDesc)))
	})
	return file_ui_notifications_proto_rawDescData
}

var file_ui_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ui_notifications_proto_goTypes = []any{
	(*Notification)(nil),      // 0: ui.Notification
	(*ConnectionState)(nil),   // 1: ui.ConnectionState
	(*DataState)(nil),         // 2: ui.DataState
	(*NoPermission)(nil),      // 3: ui.NoPermission
	(*GetStatusResponse)(nil), // 4: ui.GetStatusResponse
}
var file_ui_notifications_proto_depIdxs = []int32{
	1, // 0: ui.Notification.conn_state:type_name -> ui.ConnectionState
	2, // 1: ui.Notification.data_state:type_name -> ui.DataState
	4, // 2: ui.Notification.status:type_name -> ui.GetStatusResponse
	3, // 3: ui.Notification.no_permission:type_name -> ui.NoPermission
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ui_notifications_proto_init() }
func file_ui_notifications_proto_init() {
	if File_ui_notifications_proto != nil {
		return
	}
	file_ui_status_proto_init()
	file_ui_notifications_proto_msgTypes[0].OneofWrappers = []any{
		(*Notification_ConnState)(nil),
		(*Notification_DataState)(nil),
		(*Notification_Status)(nil),
		(*Notification_NoPermission)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ui_notifications_proto_rawDesc), len(file_ui_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ui_notifications_proto_goTypes,
		DependencyIndexes: file_ui_notifications_proto_depIdxs,
		MessageInfos:      file_ui_notifications_proto_msgTypes,
	}.Build()
	File_ui_notifications_proto = out.File
	file_ui_notifications_proto_goTypes = nil
	file_ui_notifications_proto_depIdxs = nil
}
