// Copyright 2020 Authors of Cilium
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.11.4
// source: ui/ui.proto

package ui

import (
	flow "github.com/cilium/cilium/api/v1/flow"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_UNKNOWN_EVENT       EventType = 0
	EventType_FLOW                EventType = 1
	EventType_K8S_NAMESPACE_STATE EventType = 2
	EventType_SERVICE_STATE       EventType = 3
	EventType_SERVICE_LINK_STATE  EventType = 4
	EventType_FLOWS               EventType = 5
	EventType_STATUS              EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "UNKNOWN_EVENT",
		1: "FLOW",
		2: "K8S_NAMESPACE_STATE",
		3: "SERVICE_STATE",
		4: "SERVICE_LINK_STATE",
		5: "FLOWS",
		6: "STATUS",
	}
	EventType_value = map[string]int32{
		"UNKNOWN_EVENT":       0,
		"FLOW":                1,
		"K8S_NAMESPACE_STATE": 2,
		"SERVICE_STATE":       3,
		"SERVICE_LINK_STATE":  4,
		"FLOWS":               5,
		"STATUS":              6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_ui_ui_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_ui_ui_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{0}
}

// IP protocols. The values of enums do not correspond to actual IP protocol numbers.
type IPProtocol int32

const (
	IPProtocol_UNKNOWN_IP_PROTOCOL IPProtocol = 0
	IPProtocol_TCP                 IPProtocol = 1
	IPProtocol_UDP                 IPProtocol = 2
	IPProtocol_ICMP_V4             IPProtocol = 3
	IPProtocol_ICMP_V6             IPProtocol = 4
)

// Enum value maps for IPProtocol.
var (
	IPProtocol_name = map[int32]string{
		0: "UNKNOWN_IP_PROTOCOL",
		1: "TCP",
		2: "UDP",
		3: "ICMP_V4",
		4: "ICMP_V6",
	}
	IPProtocol_value = map[string]int32{
		"UNKNOWN_IP_PROTOCOL": 0,
		"TCP":                 1,
		"UDP":                 2,
		"ICMP_V4":             3,
		"ICMP_V6":             4,
	}
)

func (x IPProtocol) Enum() *IPProtocol {
	p := new(IPProtocol)
	*p = x
	return p
}

func (x IPProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_ui_ui_proto_enumTypes[1].Descriptor()
}

func (IPProtocol) Type() protoreflect.EnumType {
	return &file_ui_ui_proto_enumTypes[1]
}

func (x IPProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPProtocol.Descriptor instead.
func (IPProtocol) EnumDescriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{1}
}

type StateChange int32

const (
	StateChange_UNKNOWN_STATE_CHANGE StateChange = 0
	StateChange_ADDED                StateChange = 1
	StateChange_MODIFIED             StateChange = 2
	StateChange_DELETED              StateChange = 3
	// This is needed in case the relay server knows that the service exists,
	// but it doesn't know when it got created.
	StateChange_EXISTS StateChange = 4
)

// Enum value maps for StateChange.
var (
	StateChange_name = map[int32]string{
		0: "UNKNOWN_STATE_CHANGE",
		1: "ADDED",
		2: "MODIFIED",
		3: "DELETED",
		4: "EXISTS",
	}
	StateChange_value = map[string]int32{
		"UNKNOWN_STATE_CHANGE": 0,
		"ADDED":                1,
		"MODIFIED":             2,
		"DELETED":              3,
		"EXISTS":               4,
	}
)

func (x StateChange) Enum() *StateChange {
	p := new(StateChange)
	*p = x
	return p
}

func (x StateChange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateChange) Descriptor() protoreflect.EnumDescriptor {
	return file_ui_ui_proto_enumTypes[2].Descriptor()
}

func (StateChange) Type() protoreflect.EnumType {
	return &file_ui_ui_proto_enumTypes[2]
}

func (x StateChange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateChange.Descriptor instead.
func (StateChange) EnumDescriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{2}
}

// Here I didn't include "follow", "until", and "number". This request assumes follow,
// and lets the client decide when to end the request, whether it's based on timestamp
// or the number of responses received.
type GetEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// EventType specifies which types of events to subscribe to. If unspecified, the
	// request is subscribed to all the event types.
	EventTypes    []EventType            `protobuf:"varint,1,rep,packed,name=event_types,json=eventTypes,proto3,enum=ui.EventType" json:"event_types,omitempty"`
	Blacklist     []*EventFilter         `protobuf:"bytes,2,rep,name=blacklist,proto3" json:"blacklist,omitempty"`
	Whitelist     []*EventFilter         `protobuf:"bytes,3,rep,name=whitelist,proto3" json:"whitelist,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	StatusRequest *GetStatusRequest      `protobuf:"bytes,5,opt,name=status_request,json=statusRequest,proto3" json:"status_request,omitempty"`
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{0}
}

func (x *GetEventsRequest) GetEventTypes() []EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *GetEventsRequest) GetBlacklist() []*EventFilter {
	if x != nil {
		return x.Blacklist
	}
	return nil
}

func (x *GetEventsRequest) GetWhitelist() []*EventFilter {
	if x != nil {
		return x.Whitelist
	}
	return nil
}

func (x *GetEventsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *GetEventsRequest) GetStatusRequest() *GetStatusRequest {
	if x != nil {
		return x.StatusRequest
	}
	return nil
}

type GetEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node      string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are assignable to Event:
	//
	//	*GetEventsResponse_Flow
	//	*GetEventsResponse_K8SNamespaceState
	//	*GetEventsResponse_ServiceState
	//	*GetEventsResponse_ServiceLinkState
	//	*GetEventsResponse_Flows
	//	*GetEventsResponse_Notification
	Event isGetEventsResponse_Event `protobuf_oneof:"event"`
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{1}
}

func (x *GetEventsResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *GetEventsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (m *GetEventsResponse) GetEvent() isGetEventsResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *GetEventsResponse) GetFlow() *flow.Flow {
	if x, ok := x.GetEvent().(*GetEventsResponse_Flow); ok {
		return x.Flow
	}
	return nil
}

func (x *GetEventsResponse) GetK8SNamespaceState() *K8SNamespaceState {
	if x, ok := x.GetEvent().(*GetEventsResponse_K8SNamespaceState); ok {
		return x.K8SNamespaceState
	}
	return nil
}

func (x *GetEventsResponse) GetServiceState() *ServiceState {
	if x, ok := x.GetEvent().(*GetEventsResponse_ServiceState); ok {
		return x.ServiceState
	}
	return nil
}

func (x *GetEventsResponse) GetServiceLinkState() *ServiceLinkState {
	if x, ok := x.GetEvent().(*GetEventsResponse_ServiceLinkState); ok {
		return x.ServiceLinkState
	}
	return nil
}

func (x *GetEventsResponse) GetFlows() *Flows {
	if x, ok := x.GetEvent().(*GetEventsResponse_Flows); ok {
		return x.Flows
	}
	return nil
}

func (x *GetEventsResponse) GetNotification() *Notification {
	if x, ok := x.GetEvent().(*GetEventsResponse_Notification); ok {
		return x.Notification
	}
	return nil
}

type isGetEventsResponse_Event interface {
	isGetEventsResponse_Event()
}

type GetEventsResponse_Flow struct {
	Flow *flow.Flow `protobuf:"bytes,3,opt,name=flow,proto3,oneof"`
}

type GetEventsResponse_K8SNamespaceState struct {
	K8SNamespaceState *K8SNamespaceState `protobuf:"bytes,4,opt,name=k8s_namespace_state,json=k8sNamespaceState,proto3,oneof"`
}

type GetEventsResponse_ServiceState struct {
	ServiceState *ServiceState `protobuf:"bytes,5,opt,name=service_state,json=serviceState,proto3,oneof"`
}

type GetEventsResponse_ServiceLinkState struct {
	// It's unclear how we can define what it means for service links to get
	// added/deleted. For now I'm deferring the decision for whether a particular
	// link should be included in the service map to the client. Maybe the server
	// can periodically send service_link events for active links to keep-alive,
	// and the client can expire older links based on their timestamp.
	ServiceLinkState *ServiceLinkState `protobuf:"bytes,6,opt,name=service_link_state,json=serviceLinkState,proto3,oneof"`
}

type GetEventsResponse_Flows struct {
	Flows *Flows `protobuf:"bytes,7,opt,name=flows,proto3,oneof"`
}

type GetEventsResponse_Notification struct {
	Notification *Notification `protobuf:"bytes,8,opt,name=notification,proto3,oneof"`
}

func (*GetEventsResponse_Flow) isGetEventsResponse_Event() {}

func (*GetEventsResponse_K8SNamespaceState) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ServiceState) isGetEventsResponse_Event() {}

func (*GetEventsResponse_ServiceLinkState) isGetEventsResponse_Event() {}

func (*GetEventsResponse_Flows) isGetEventsResponse_Event() {}

func (*GetEventsResponse_Notification) isGetEventsResponse_Event() {}

type Flows struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flows []*flow.Flow `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
}

func (x *Flows) Reset() {
	*x = Flows{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flows) ProtoMessage() {}

func (x *Flows) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flows.ProtoReflect.Descriptor instead.
func (*Flows) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{2}
}

func (x *Flows) GetFlows() []*flow.Flow {
	if x != nil {
		return x.Flows
	}
	return nil
}

// Here I added different filter types for different events. Another option is to reuse
// and extend FlowFilter to filter all the events, but I worry that it might become too
// confusing in terms of figuring out which filter fields apply to which events.
type EventFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Filter:
	//
	//	*EventFilter_FlowFilter
	//	*EventFilter_ServiceFilter
	//	*EventFilter_ServiceLinkFilter
	Filter isEventFilter_Filter `protobuf_oneof:"filter"`
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{3}
}

func (m *EventFilter) GetFilter() isEventFilter_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (x *EventFilter) GetFlowFilter() *flow.FlowFilter {
	if x, ok := x.GetFilter().(*EventFilter_FlowFilter); ok {
		return x.FlowFilter
	}
	return nil
}

func (x *EventFilter) GetServiceFilter() *ServiceFilter {
	if x, ok := x.GetFilter().(*EventFilter_ServiceFilter); ok {
		return x.ServiceFilter
	}
	return nil
}

func (x *EventFilter) GetServiceLinkFilter() *ServiceLinkFilter {
	if x, ok := x.GetFilter().(*EventFilter_ServiceLinkFilter); ok {
		return x.ServiceLinkFilter
	}
	return nil
}

type isEventFilter_Filter interface {
	isEventFilter_Filter()
}

type EventFilter_FlowFilter struct {
	FlowFilter *flow.FlowFilter `protobuf:"bytes,2,opt,name=flow_filter,json=flowFilter,proto3,oneof"`
}

type EventFilter_ServiceFilter struct {
	ServiceFilter *ServiceFilter `protobuf:"bytes,3,opt,name=service_filter,json=serviceFilter,proto3,oneof"`
}

type EventFilter_ServiceLinkFilter struct {
	ServiceLinkFilter *ServiceLinkFilter `protobuf:"bytes,4,opt,name=service_link_filter,json=serviceLinkFilter,proto3,oneof"`
}

func (*EventFilter_FlowFilter) isEventFilter_Filter() {}

func (*EventFilter_ServiceFilter) isEventFilter_Filter() {}

func (*EventFilter_ServiceLinkFilter) isEventFilter_Filter() {}

type K8SNamespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreationTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
}

func (x *K8SNamespace) Reset() {
	*x = K8SNamespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *K8SNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNamespace) ProtoMessage() {}

func (x *K8SNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNamespace.ProtoReflect.Descriptor instead.
func (*K8SNamespace) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{4}
}

func (x *K8SNamespace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *K8SNamespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *K8SNamespace) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

type K8SNamespaceState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace *K8SNamespace `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type      StateChange   `protobuf:"varint,2,opt,name=type,proto3,enum=ui.StateChange" json:"type,omitempty"`
}

func (x *K8SNamespaceState) Reset() {
	*x = K8SNamespaceState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *K8SNamespaceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SNamespaceState) ProtoMessage() {}

func (x *K8SNamespaceState) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SNamespaceState.ProtoReflect.Descriptor instead.
func (*K8SNamespaceState) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{5}
}

func (x *K8SNamespaceState) GetNamespace() *K8SNamespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *K8SNamespaceState) GetType() StateChange {
	if x != nil {
		return x.Type
	}
	return StateChange_UNKNOWN_STATE_CHANGE
}

// Come up with a better name for Service.
type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An opaque ID that uniquely identifies the service.
	Id                    string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace             string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels                []string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	DnsNames              []string `protobuf:"bytes,5,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	EgressPolicyEnforced  bool     `protobuf:"varint,6,opt,name=egress_policy_enforced,json=egressPolicyEnforced,proto3" json:"egress_policy_enforced,omitempty"`
	IngressPolicyEnforced bool     `protobuf:"varint,7,opt,name=ingress_policy_enforced,json=ingressPolicyEnforced,proto3" json:"ingress_policy_enforced,omitempty"`
	// This is a string instead of boolean because Cilium reports status message. If it's
	// successfully enabled, this string is set to "OK" I think.
	VisibilityPolicyStatus string `protobuf:"bytes,8,opt,name=visibility_policy_status,json=visibilityPolicyStatus,proto3" json:"visibility_policy_status,omitempty"`
	// We probably can't reliably set creation timestamp.
	CreationTimestamp *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{6}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Service) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Service) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *Service) GetEgressPolicyEnforced() bool {
	if x != nil {
		return x.EgressPolicyEnforced
	}
	return false
}

func (x *Service) GetIngressPolicyEnforced() bool {
	if x != nil {
		return x.IngressPolicyEnforced
	}
	return false
}

func (x *Service) GetVisibilityPolicyStatus() string {
	if x != nil {
		return x.VisibilityPolicyStatus
	}
	return ""
}

func (x *Service) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

type ServiceState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *Service    `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Type    StateChange `protobuf:"varint,2,opt,name=type,proto3,enum=ui.StateChange" json:"type,omitempty"`
}

func (x *ServiceState) Reset() {
	*x = ServiceState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceState) ProtoMessage() {}

func (x *ServiceState) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceState.ProtoReflect.Descriptor instead.
func (*ServiceState) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceState) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceState) GetType() StateChange {
	if x != nil {
		return x.Type
	}
	return StateChange_UNKNOWN_STATE_CHANGE
}

type ServiceFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace []string `protobuf:"bytes,1,rep,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *ServiceFilter) Reset() {
	*x = ServiceFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceFilter) ProtoMessage() {}

func (x *ServiceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceFilter.ProtoReflect.Descriptor instead.
func (*ServiceFilter) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceFilter) GetNamespace() []string {
	if x != nil {
		return x.Namespace
	}
	return nil
}

type ServiceLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An opaque ID that uniquely identifies this link.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// source Service id
	SourceId string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// destination Service id
	DestinationId   string        `protobuf:"bytes,3,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	DestinationPort uint32        `protobuf:"varint,4,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	IpProtocol      IPProtocol    `protobuf:"varint,5,opt,name=ip_protocol,json=ipProtocol,proto3,enum=ui.IPProtocol" json:"ip_protocol,omitempty"`
	Verdict         flow.Verdict  `protobuf:"varint,6,opt,name=verdict,proto3,enum=flow.Verdict" json:"verdict,omitempty"`
	AuthType        flow.AuthType `protobuf:"varint,7,opt,name=auth_type,json=authType,proto3,enum=flow.AuthType" json:"auth_type,omitempty"`
	IsEncrypted     bool          `protobuf:"varint,8,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
}

func (x *ServiceLink) Reset() {
	*x = ServiceLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLink) ProtoMessage() {}

func (x *ServiceLink) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLink.ProtoReflect.Descriptor instead.
func (*ServiceLink) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceLink) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ServiceLink) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *ServiceLink) GetDestinationPort() uint32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *ServiceLink) GetIpProtocol() IPProtocol {
	if x != nil {
		return x.IpProtocol
	}
	return IPProtocol_UNKNOWN_IP_PROTOCOL
}

func (x *ServiceLink) GetVerdict() flow.Verdict {
	if x != nil {
		return x.Verdict
	}
	return flow.Verdict(0)
}

func (x *ServiceLink) GetAuthType() flow.AuthType {
	if x != nil {
		return x.AuthType
	}
	return flow.AuthType(0)
}

func (x *ServiceLink) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

type ServiceLinkState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceLink *ServiceLink `protobuf:"bytes,1,opt,name=service_link,json=serviceLink,proto3" json:"service_link,omitempty"`
	Type        StateChange  `protobuf:"varint,2,opt,name=type,proto3,enum=ui.StateChange" json:"type,omitempty"`
}

func (x *ServiceLinkState) Reset() {
	*x = ServiceLinkState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceLinkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLinkState) ProtoMessage() {}

func (x *ServiceLinkState) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLinkState.ProtoReflect.Descriptor instead.
func (*ServiceLinkState) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceLinkState) GetServiceLink() *ServiceLink {
	if x != nil {
		return x.ServiceLink
	}
	return nil
}

func (x *ServiceLinkState) GetType() StateChange {
	if x != nil {
		return x.Type
	}
	return StateChange_UNKNOWN_STATE_CHANGE
}

type ServiceLinkFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      []*ServiceFilter `protobuf:"bytes,1,rep,name=source,proto3" json:"source,omitempty"`
	Destination []*ServiceFilter `protobuf:"bytes,2,rep,name=destination,proto3" json:"destination,omitempty"`
	// Use string here to support things like port ranges (e.g. 100-200).
	DestinationPort []string       `protobuf:"bytes,3,rep,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Verdict         []flow.Verdict `protobuf:"varint,4,rep,packed,name=verdict,proto3,enum=flow.Verdict" json:"verdict,omitempty"`
}

func (x *ServiceLinkFilter) Reset() {
	*x = ServiceLinkFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceLinkFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLinkFilter) ProtoMessage() {}

func (x *ServiceLinkFilter) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLinkFilter.ProtoReflect.Descriptor instead.
func (*ServiceLinkFilter) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceLinkFilter) GetSource() []*ServiceFilter {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ServiceLinkFilter) GetDestination() []*ServiceFilter {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *ServiceLinkFilter) GetDestinationPort() []string {
	if x != nil {
		return x.DestinationPort
	}
	return nil
}

func (x *ServiceLinkFilter) GetVerdict() []flow.Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

type GetControlStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetControlStreamRequest) Reset() {
	*x = GetControlStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetControlStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlStreamRequest) ProtoMessage() {}

func (x *GetControlStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlStreamRequest.ProtoReflect.Descriptor instead.
func (*GetControlStreamRequest) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{12}
}

type GetControlStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*GetControlStreamResponse_Namespaces
	//	*GetControlStreamResponse_Notification
	Event isGetControlStreamResponse_Event `protobuf_oneof:"event"`
}

func (x *GetControlStreamResponse) Reset() {
	*x = GetControlStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetControlStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlStreamResponse) ProtoMessage() {}

func (x *GetControlStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlStreamResponse.ProtoReflect.Descriptor instead.
func (*GetControlStreamResponse) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{13}
}

func (m *GetControlStreamResponse) GetEvent() isGetControlStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *GetControlStreamResponse) GetNamespaces() *GetControlStreamResponse_NamespaceStates {
	if x, ok := x.GetEvent().(*GetControlStreamResponse_Namespaces); ok {
		return x.Namespaces
	}
	return nil
}

func (x *GetControlStreamResponse) GetNotification() *Notification {
	if x, ok := x.GetEvent().(*GetControlStreamResponse_Notification); ok {
		return x.Notification
	}
	return nil
}

type isGetControlStreamResponse_Event interface {
	isGetControlStreamResponse_Event()
}

type GetControlStreamResponse_Namespaces struct {
	Namespaces *GetControlStreamResponse_NamespaceStates `protobuf:"bytes,1,opt,name=namespaces,proto3,oneof"`
}

type GetControlStreamResponse_Notification struct {
	Notification *Notification `protobuf:"bytes,2,opt,name=notification,proto3,oneof"`
}

func (*GetControlStreamResponse_Namespaces) isGetControlStreamResponse_Event() {}

func (*GetControlStreamResponse_Notification) isGetControlStreamResponse_Event() {}

type GetControlStreamResponse_NamespaceStates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespaces []*K8SNamespaceState `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
}

func (x *GetControlStreamResponse_NamespaceStates) Reset() {
	*x = GetControlStreamResponse_NamespaceStates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ui_ui_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetControlStreamResponse_NamespaceStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlStreamResponse_NamespaceStates) ProtoMessage() {}

func (x *GetControlStreamResponse_NamespaceStates) ProtoReflect() protoreflect.Message {
	mi := &file_ui_ui_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlStreamResponse_NamespaceStates.ProtoReflect.Descriptor instead.
func (*GetControlStreamResponse_NamespaceStates) Descriptor() ([]byte, []int) {
	return file_ui_ui_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GetControlStreamResponse_NamespaceStates) GetNamespaces() []*K8SNamespaceState {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

var File_ui_ui_proto protoreflect.FileDescriptor

var file_ui_ui_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x75, 0x69, 0x2f, 0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x75,
	0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0f, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x75, 0x69, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x75, 0x69, 0x2f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x02, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x75, 0x69, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x12, 0x2d, 0x0a, 0x09, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x69, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x09, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x2d, 0x0a, 0x09, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75, 0x69, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x09, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x30, 0x0a, 0x05, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x69, 0x6e, 0x63,
	0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xaf,
	0x03, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x20, 0x0a, 0x04, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x48, 0x00, 0x52, 0x04,
	0x66, 0x6c, 0x6f, 0x77, 0x12, 0x47, 0x0a, 0x13, 0x6b, 0x38, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x75, 0x69, 0x2e, 0x4b, 0x38, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x11, 0x6b, 0x38, 0x73, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x37, 0x0a,
	0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c,
	0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x05,
	0x66, 0x6c, 0x6f, 0x77, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x75, 0x69,
	0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x73, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x12,
	0x36, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x69, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x29, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x77, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x66, 0x6c, 0x6f,
	0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e,
	0x46, 0x6c, 0x6f, 0x77, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x0b,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x0b, 0x66,
	0x6c, 0x6f, 0x77, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x46, 0x6c, 0x6f, 0x77, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x77, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x3a, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x13,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x69, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x7d, 0x0a, 0x0c, 0x4b, 0x38, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x49, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x11, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x68,
	0x0a, 0x11, 0x4b, 0x38, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x69, 0x2e, 0x4b, 0x38, 0x73, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xf3, 0x02, 0x0a, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x6e, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x6e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x16, 0x65,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x65, 0x6e, 0x66,
	0x6f, 0x72, 0x63, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x65, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65,
	0x64, 0x12, 0x36, 0x0a, 0x17, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x5f, 0x65, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x15, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x45, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x18, 0x76, 0x69, 0x73,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x76, 0x69, 0x73,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x49, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x11, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5a,
	0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25,
	0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2d, 0x0a, 0x0d, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xb6, 0x02, 0x0a, 0x0b, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a,
	0x10, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x2f, 0x0a, 0x0b, 0x69, 0x70, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x75, 0x69, 0x2e, 0x49, 0x50, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x0a, 0x69,
	0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x27, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x64, 0x69, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x52, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69,
	0x63, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x22, 0x6b, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6e,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x75,
	0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0xc7, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x33, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x69, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x27, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xf5, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4e, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x75, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x12, 0x36, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x69, 0x2e, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x48, 0x0a, 0x0f, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0a,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x75, 0x69, 0x2e, 0x4b, 0x38, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2a, 0x83, 0x01, 0x0a,
	0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x46, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x4b, 0x38, 0x53, 0x5f, 0x4e,
	0x41, 0x4d, 0x45, 0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x02,
	0x12, 0x11, 0x0a, 0x0d, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x4c,
	0x49, 0x4e, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x46,
	0x4c, 0x4f, 0x57, 0x53, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x10, 0x06, 0x2a, 0x51, 0x0a, 0x0a, 0x49, 0x50, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x12, 0x17, 0x0a, 0x13, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x49, 0x50, 0x5f, 0x50,
	0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x43, 0x4d, 0x50, 0x5f, 0x56, 0x34, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x43, 0x4d, 0x50,
	0x5f, 0x56, 0x36, 0x10, 0x04, 0x2a, 0x59, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x44, 0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x4f, 0x44,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x04,
	0x32, 0xcf, 0x01, 0x0a, 0x02, 0x55, 0x49, 0x12, 0x3c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x75, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x75, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x2e, 0x75, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x75, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1b, 0x2e, 0x75, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ui_ui_proto_rawDescOnce sync.Once
	file_ui_ui_proto_rawDescData = file_ui_ui_proto_rawDesc
)

func file_ui_ui_proto_rawDescGZIP() []byte {
	file_ui_ui_proto_rawDescOnce.Do(func() {
		file_ui_ui_proto_rawDescData = protoimpl.X.CompressGZIP(file_ui_ui_proto_rawDescData)
	})
	return file_ui_ui_proto_rawDescData
}

var file_ui_ui_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ui_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ui_ui_proto_goTypes = []interface{}{
	(EventType)(0),                                   // 0: ui.EventType
	(IPProtocol)(0),                                  // 1: ui.IPProtocol
	(StateChange)(0),                                 // 2: ui.StateChange
	(*GetEventsRequest)(nil),                         // 3: ui.GetEventsRequest
	(*GetEventsResponse)(nil),                        // 4: ui.GetEventsResponse
	(*Flows)(nil),                                    // 5: ui.Flows
	(*EventFilter)(nil),                              // 6: ui.EventFilter
	(*K8SNamespace)(nil),                             // 7: ui.K8sNamespace
	(*K8SNamespaceState)(nil),                        // 8: ui.K8sNamespaceState
	(*Service)(nil),                                  // 9: ui.Service
	(*ServiceState)(nil),                             // 10: ui.ServiceState
	(*ServiceFilter)(nil),                            // 11: ui.ServiceFilter
	(*ServiceLink)(nil),                              // 12: ui.ServiceLink
	(*ServiceLinkState)(nil),                         // 13: ui.ServiceLinkState
	(*ServiceLinkFilter)(nil),                        // 14: ui.ServiceLinkFilter
	(*GetControlStreamRequest)(nil),                  // 15: ui.GetControlStreamRequest
	(*GetControlStreamResponse)(nil),                 // 16: ui.GetControlStreamResponse
	(*GetControlStreamResponse_NamespaceStates)(nil), // 17: ui.GetControlStreamResponse.NamespaceStates
	(*timestamppb.Timestamp)(nil),                    // 18: google.protobuf.Timestamp
	(*GetStatusRequest)(nil),                         // 19: ui.GetStatusRequest
	(*flow.Flow)(nil),                                // 20: flow.Flow
	(*Notification)(nil),                             // 21: ui.Notification
	(*flow.FlowFilter)(nil),                          // 22: flow.FlowFilter
	(flow.Verdict)(0),                                // 23: flow.Verdict
	(flow.AuthType)(0),                               // 24: flow.AuthType
	(*GetStatusResponse)(nil),                        // 25: ui.GetStatusResponse
}
var file_ui_ui_proto_depIdxs = []int32{
	0,  // 0: ui.GetEventsRequest.event_types:type_name -> ui.EventType
	6,  // 1: ui.GetEventsRequest.blacklist:type_name -> ui.EventFilter
	6,  // 2: ui.GetEventsRequest.whitelist:type_name -> ui.EventFilter
	18, // 3: ui.GetEventsRequest.since:type_name -> google.protobuf.Timestamp
	19, // 4: ui.GetEventsRequest.status_request:type_name -> ui.GetStatusRequest
	18, // 5: ui.GetEventsResponse.timestamp:type_name -> google.protobuf.Timestamp
	20, // 6: ui.GetEventsResponse.flow:type_name -> flow.Flow
	8,  // 7: ui.GetEventsResponse.k8s_namespace_state:type_name -> ui.K8sNamespaceState
	10, // 8: ui.GetEventsResponse.service_state:type_name -> ui.ServiceState
	13, // 9: ui.GetEventsResponse.service_link_state:type_name -> ui.ServiceLinkState
	5,  // 10: ui.GetEventsResponse.flows:type_name -> ui.Flows
	21, // 11: ui.GetEventsResponse.notification:type_name -> ui.Notification
	20, // 12: ui.Flows.flows:type_name -> flow.Flow
	22, // 13: ui.EventFilter.flow_filter:type_name -> flow.FlowFilter
	11, // 14: ui.EventFilter.service_filter:type_name -> ui.ServiceFilter
	14, // 15: ui.EventFilter.service_link_filter:type_name -> ui.ServiceLinkFilter
	18, // 16: ui.K8sNamespace.creation_timestamp:type_name -> google.protobuf.Timestamp
	7,  // 17: ui.K8sNamespaceState.namespace:type_name -> ui.K8sNamespace
	2,  // 18: ui.K8sNamespaceState.type:type_name -> ui.StateChange
	18, // 19: ui.Service.creation_timestamp:type_name -> google.protobuf.Timestamp
	9,  // 20: ui.ServiceState.service:type_name -> ui.Service
	2,  // 21: ui.ServiceState.type:type_name -> ui.StateChange
	1,  // 22: ui.ServiceLink.ip_protocol:type_name -> ui.IPProtocol
	23, // 23: ui.ServiceLink.verdict:type_name -> flow.Verdict
	24, // 24: ui.ServiceLink.auth_type:type_name -> flow.AuthType
	12, // 25: ui.ServiceLinkState.service_link:type_name -> ui.ServiceLink
	2,  // 26: ui.ServiceLinkState.type:type_name -> ui.StateChange
	11, // 27: ui.ServiceLinkFilter.source:type_name -> ui.ServiceFilter
	11, // 28: ui.ServiceLinkFilter.destination:type_name -> ui.ServiceFilter
	23, // 29: ui.ServiceLinkFilter.verdict:type_name -> flow.Verdict
	17, // 30: ui.GetControlStreamResponse.namespaces:type_name -> ui.GetControlStreamResponse.NamespaceStates
	21, // 31: ui.GetControlStreamResponse.notification:type_name -> ui.Notification
	8,  // 32: ui.GetControlStreamResponse.NamespaceStates.namespaces:type_name -> ui.K8sNamespaceState
	3,  // 33: ui.UI.GetEvents:input_type -> ui.GetEventsRequest
	19, // 34: ui.UI.GetStatus:input_type -> ui.GetStatusRequest
	15, // 35: ui.UI.GetControlStream:input_type -> ui.GetControlStreamRequest
	4,  // 36: ui.UI.GetEvents:output_type -> ui.GetEventsResponse
	25, // 37: ui.UI.GetStatus:output_type -> ui.GetStatusResponse
	16, // 38: ui.UI.GetControlStream:output_type -> ui.GetControlStreamResponse
	36, // [36:39] is the sub-list for method output_type
	33, // [33:36] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_ui_ui_proto_init() }
func file_ui_ui_proto_init() {
	if File_ui_ui_proto != nil {
		return
	}
	file_ui_notifications_proto_init()
	file_ui_status_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ui_ui_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flows); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*K8SNamespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*K8SNamespaceState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceLinkState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceLinkFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetControlStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetControlStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ui_ui_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetControlStreamResponse_NamespaceStates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ui_ui_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GetEventsResponse_Flow)(nil),
		(*GetEventsResponse_K8SNamespaceState)(nil),
		(*GetEventsResponse_ServiceState)(nil),
		(*GetEventsResponse_ServiceLinkState)(nil),
		(*GetEventsResponse_Flows)(nil),
		(*GetEventsResponse_Notification)(nil),
	}
	file_ui_ui_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*EventFilter_FlowFilter)(nil),
		(*EventFilter_ServiceFilter)(nil),
		(*EventFilter_ServiceLinkFilter)(nil),
	}
	file_ui_ui_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*GetControlStreamResponse_Namespaces)(nil),
		(*GetControlStreamResponse_Notification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ui_ui_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ui_ui_proto_goTypes,
		DependencyIndexes: file_ui_ui_proto_depIdxs,
		EnumInfos:         file_ui_ui_proto_enumTypes,
		MessageInfos:      file_ui_ui_proto_msgTypes,
	}.Build()
	File_ui_ui_proto = out.File
	file_ui_ui_proto_rawDesc = nil
	file_ui_ui_proto_goTypes = nil
	file_ui_ui_proto_depIdxs = nil
}
