// source: relay/relay.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.relay.NodeState', null, global);
goog.exportSymbol('proto.relay.NodeStatusEvent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.NodeStatusEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.relay.NodeStatusEvent.repeatedFields_, null);
};
goog.inherits(proto.relay.NodeStatusEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.NodeStatusEvent.displayName = 'proto.relay.NodeStatusEvent';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.relay.NodeStatusEvent.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.NodeStatusEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.NodeStatusEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.NodeStatusEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.NodeStatusEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    stateChange: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nodeNamesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    message: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.NodeStatusEvent}
 */
proto.relay.NodeStatusEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.NodeStatusEvent;
  return proto.relay.NodeStatusEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.NodeStatusEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.NodeStatusEvent}
 */
proto.relay.NodeStatusEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.relay.NodeState} */ (reader.readEnum());
      msg.setStateChange(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addNodeNames(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.NodeStatusEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.NodeStatusEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.NodeStatusEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.NodeStatusEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStateChange();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getNodeNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional NodeState state_change = 1;
 * @return {!proto.relay.NodeState}
 */
proto.relay.NodeStatusEvent.prototype.getStateChange = function() {
  return /** @type {!proto.relay.NodeState} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.relay.NodeState} value
 * @return {!proto.relay.NodeStatusEvent} returns this
 */
proto.relay.NodeStatusEvent.prototype.setStateChange = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * repeated string node_names = 2;
 * @return {!Array<string>}
 */
proto.relay.NodeStatusEvent.prototype.getNodeNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.relay.NodeStatusEvent} returns this
 */
proto.relay.NodeStatusEvent.prototype.setNodeNamesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.relay.NodeStatusEvent} returns this
 */
proto.relay.NodeStatusEvent.prototype.addNodeNames = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.relay.NodeStatusEvent} returns this
 */
proto.relay.NodeStatusEvent.prototype.clearNodeNamesList = function() {
  return this.setNodeNamesList([]);
};


/**
 * optional string message = 3;
 * @return {string}
 */
proto.relay.NodeStatusEvent.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.NodeStatusEvent} returns this
 */
proto.relay.NodeStatusEvent.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.relay.NodeState = {
  UNKNOWN_NODE_STATE: 0,
  NODE_CONNECTED: 1,
  NODE_UNAVAILABLE: 2,
  NODE_GONE: 3,
  NODE_ERROR: 4
};

goog.object.extend(exports, proto.relay);
