name: Build Image
on:
  push:
    branches:
      - master
      - v.*
    tags:
      - v.*
  pull_request:
    branches:
    - master
    - v.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build Image
      run: |
        docker build .
