name: Build docker image
on: push
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build Image
        run: |
          docker build .
